### PR TITLE
Python 3.4 import fix

### LINKED ISSUE #7: Version 1.2.1 does not run - ImportError: cannot import name 'rockstar'
After a fresh install of Python 3.4 via package manager (onto CentOS 7), followed by pip3 and `sudo pip3 install rockstar-py`, running `rockstar-py` gives the following error:

```
[vagrant@adpc-com-039 Python-3.7.0]$ rockstar-py
Traceback (most recent call last):
  File "/usr/bin/rockstar-py", line 9, in <module>
    load_entry_point('rockstar-py==1.2.1', 'console_scripts', 'rockstar-py')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2719, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2379, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2385, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/rockstarpy/__init__.py", line 1, in <module>
    from . import rockstar
  File "/usr/lib/python3.4/site-packages/rockstarpy/rockstar.py", line 2, in <module>
    from . import command_line
  File "/usr/lib/python3.4/site-packages/rockstarpy/command_line.py", line 2, in <module>
    from . import rockstar
ImportError: cannot import name 'rockstar'
```

### PR DESCRIPTION
**Pull request by jmsv**
Fixes #7 :sparkles::stars:

__Changed import structure to work with Python 3.3 and 3.4__

- Travis config has been added for automating test runs on commit
- Added [Python `.gitignore`](https://github.com/github/gitignore/blob/master/Python.gitignore)

### CODE REVIEW

**Comment by jmsv** [comment]
I recommending enabling Travis CI for this repo for running tests automatically on new commits including PRs

**Comment by yanorestes** [comment]
Thanks a lot, @jmsv! Just enabled Travis CI
